apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: weather-dashboard
spec:
  to:
    kind: Service
    name: weather-frontend
  port:
    targetPort: 8080
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect