FROM node:20-alpine AS builder
WORKDIR /app
COPY package*.json ./

RUN npm ci
COPY . .

FROM node:20-alpine AS dependency-cleaner
WORKDIR /app
COPY package*.json ./
RUN npm ci --only=production

FROM node:20-alpine
WORKDIR /app
ENV NODE_ENV=production

COPY --from=dependency-cleaner /app/node_modules ./node_modules
COPY --from=builder /app/package.json ./package.json

COPY . .

USER node

EXPOSE 3000
CMD ["node", "app.js"]
