# ─── Aplicación ──────────────────────────────────────────────────
quarkus.application.name=notificacion-api

# ─── Base de datos ────────────────────────────────────────────────
quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=${DB_USER:workshop}
quarkus.datasource.password=${DB_PASSWORD:workshop123}
quarkus.datasource.jdbc.url=jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:tienda}

quarkus.hibernate-orm.database.generation=update
quarkus.hibernate-orm.database.default-schema=notificaciones
quarkus.hibernate-orm.log.sql=false

# ─── OpenTelemetry ───────────────────────────────────────────────
quarkus.otel.exporter.otlp.traces.endpoint=${OTEL_EXPORTER_OTLP_ENDPOINT:http://otel-collector:4317}
quarkus.otel.exporter.otlp.traces.protocol=grpc
quarkus.otel.resource.attributes=service.name=notificacion-api,service.version=1.0.0,deployment.environment=workshop

# ─── Logging ─────────────────────────────────────────────────────
quarkus.log.console.json=true
quarkus.log.console.json.additional-field."service".value=notificacion-api
quarkus.log.level=INFO

# ─── HTTP ────────────────────────────────────────────────────────
quarkus.http.port=8080
quarkus.http.access-log.enabled=true

# ─── Health ──────────────────────────────────────────────────────
quarkus.smallrye-health.root-path=/health

# ─── Métricas ────────────────────────────────────────────────────
quarkus.micrometer.export.prometheus.path=/q/metrics

# ─── Dev mode ────────────────────────────────────────────────────
%dev.quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5432/tienda
%dev.quarkus.hibernate-orm.log.sql=true
%dev.quarkus.otel.exporter.otlp.traces.endpoint=http://localhost:4317
