quarkus.http.port=8080
quarkus.application.name=quarkus-demo
quarkus.application.version=1.0.0

# Logging
quarkus.log.level=INFO
quarkus.log.console.format=%d{HH:mm:ss} %-5p [%c{2.}] %s%e%n

# Health
quarkus.smallrye-health.root-path=/health

# Package: fast-jar (default — genera target/quarkus-app/)
quarkus.package.jar.type=fast-jar
