---
apiVersion: tempo.openshift.io/v1alpha1
kind: TempoStack
metadata:
  name: todo-tempo
  namespace: todo
spec:
  storage:
    secret:
      name: tempo-storage-secret
  query:
    enabled: true
  resources:
    total:
      limits:
        memory: "1Gi"
        cpu: "500m"
