apiVersion: v1
kind: Secret
metadata:
  name: github-credentials
  namespace: openshift-pipelines
type: Opaque
stringData:
  .git-credentials: |
    https://<user>:<token>@github.com
  .gitconfig: |
    [credential]
        helper = store
