apiVersion: v1
kind: Secret
metadata:
  name: quay-robot-account-secret
  namespace: openshift-pipelines
type: kubernetes.io/dockerconfigjson
stringData:
  .dockerconfigjson: |
    {
      "auths": {
            "quay-registry-quay-quay.apps.cluster-kc4hf.dynamic.redhatworkshops.io/developer": {
               "auth": "ZGV2ZWxvcGVyK3dvcmtzaG9wOjBSWVNXRjBPVUMzTUpDRzhNMFNHU1dVWFNTMjk3NzNTUUJNVU4yUjY2RVhPUklFQVNJNVYzUURDS0o4QjZXME4=",
               "email": ""
        }
      }
    }
