apiVersion: apps/v1
kind: Deployment
metadata:
  name: test
  namespace: kuard
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test
  template:
    metadata:
      labels:
        app: test
    spec:
      containers:
      - name: test
        image: default-route-openshift-image-registry.apps.cluster-8tsrm.dynamic.redhatworkshops.io/kuard/test:1
        ports:
        - containerPort: 8080
